name: Build Image On Commit

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  packages: write
  contents: read
jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.0'

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          make build-docker-image

      - name: Push image
        env:
          NAMESPACE: ${{ github.repository_owner }}
          IMAGE_NAME: im-to-notion
        run: |
          IMAGE_ID=ghcr.io/$NAMESPACE/$IMAGE_NAME
          
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:dev $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
